# ----
# Site

title: Sam's Blog
url: "https://blog.samhinshaw.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! Here I'll be reporting my journey learning
  full stack web development (with a focus on front-end). I'm doing
  this mostly for my own benefit, to have a resource to look back on.
  
# Author details for the jekyll-seo-tag gem
author:
  name: Sam Hinshaw
  email: sam@samhinshaw.com
  twitter: samhinshaw

# Social details for the jekyll-seo-tag gem
social:
  name: Sam Hinshaw's Blog
  links:
    - https://github.com/samhinshaw/blog
# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
